Cora:
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 512
  activation: 'prelu'
  base_model: 'GCNConv'
  cost_type: 'cos'
  distance: 'emd'
  drop_feature_rate_1: 0.4
  drop_feature_rate_2: 0.3
  keep_prob_1: 0.5
  keep_prob_2: 0.4
  p: 0.5
  num_epochs: 500
  tau: 0.5
  weight_decay: 0.00001
  drop_scheme: 'rand'
  num_epochs: 100
  num_layers: 2
