Cora:
  activation: 'prelu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.6
  drop_feature_rate_2: 0.9
  keep_prob_1: 0.3
  keep_prob_2: 0.8
  p: 0.4
  learning_rate: 0.01  
  num_epochs: 2100
  num_hidden: 512
  num_proj_hidden: 256
  reg_lambda: 0.001
  tau: 0.8
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Citeseer:
  activation: 'prelu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.7
  drop_feature_rate_2: 0.9
  keep_prob_1: 0.3
  keep_prob_2: 0.9
  p: 0.1
  learning_rate: 0.001  
  num_epochs: 2000
  num_hidden: 512
  num_proj_hidden: 512
  reg_lambda: 0.001
  tau: 0.3
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Pubmed:
  activation: 'relu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.5
  keep_prob_1: 0.6
  keep_prob_2: 0.7
  p: 0.8
  learning_rate: 0.01  
  num_epochs: 800
  num_hidden: 512
  num_proj_hidden: 512
  reg_lambda: 0.001
  tau: 0.5
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Texas:
  activation: 'prelu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.2
  keep_prob_1: 0.3
  keep_prob_2: 0.4
  p: 0.7
  learning_rate: 0.01  
  num_epochs: 1700
  num_hidden: 256
  num_proj_hidden: 128
  reg_lambda: 0.001
  tau: 0.9
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Wisconsin:
  activation: 'prelu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.9
  keep_prob_1: 0.2
  keep_prob_2: 0.4
  p: 0.7
  learning_rate: 0.005  
  num_epochs: 900
  num_hidden: 256
  num_proj_hidden: 512
  reg_lambda: 0.001
  tau: 0.3
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Cornell:
  activation: 'relu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.2
  keep_prob_1: 0.1
  keep_prob_2: 0.2
  p: 0.8
  learning_rate: 0.01  
  num_epochs: 2800
  num_hidden: 256
  num_proj_hidden: 512
  reg_lambda: 0.001
  tau: 0.3
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Chameleon:
  activation: 'prelu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.5
  keep_prob_1: 0.5
  keep_prob_2: 0.7
  p: 0.5
  learning_rate: 0.005  
  num_epochs: 2600
  num_hidden: 512
  num_proj_hidden: 256
  reg_lambda: 0.001
  tau: 0.4
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2

Squirrel:
  activation: 'prelu'
  base_model: 'GCNConv'
  distance: 'emd'
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  keep_prob_1: 0.5
  keep_prob_2: 0.6
  p: 0.8
  learning_rate: 0.01  
  num_epochs: 800
  num_hidden: 512
  num_proj_hidden: 256
  reg_lambda: 0.001
  tau: 0.9
  weight_decay: 0.00001
  drop_scheme: 'rand'
  cost_type: 'cos'
  num_layers: 2